name: nipibasket_tupizarravirtual
description: "A new Flutter project."
publish_to: 'none' 
version: 1.3.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1  
  firebase_auth: ^5.3.3
  provider: ^6.1.2
  fluttertoast: ^8.2.2 
  crypto: ^3.0.0
  url_launcher: ^6.1.11
  table_calendar: ^3.0.9
  cloud_firestore: ^5.6.8
  video_player: ^2.7.0
  chewie: ^1.4.0
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  permission_handler: ^12.0.0+1
  firebase_storage: ^12.3.0
  google_sign_in: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 
  test: ^1.24.0

flutter_launcher_icons:
  android: true  
  ios: true      
  image_path: "lib/assets/icon/icono.png"  
  remove_alpha_ios: true  

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/icono.png
    - lib/assets/icon/canasta.png
    - lib/assets/icon/cancha_baloncesto.png
    - lib/assets/icon/google_logo.webp
