// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUQ_-2MNxJV7GYIUGvHPVLJ1sAr-Dw5I',
    appId: '1:830352231306:web:9d665d576e24b4f5b41673',
    messagingSenderId: '830352231306',
    projectId: 'nipibaskettupizarravirtual',
    authDomain: 'nipibaskettupizarravirtual.firebaseapp.com',
    storageBucket: 'nipibaskettupizarravirtual.firebasestorage.app',
    measurementId: 'G-Z5QB8NS7S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzoPQJoZeA8aKBsUSB-unvukT5QVmVCUc',
    appId: '1:830352231306:android:624047c830e0324fb41673',
    messagingSenderId: '830352231306',
    projectId: 'nipibaskettupizarravirtual',
    storageBucket: 'nipibaskettupizarravirtual.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZLyOMm_gMsz10QT2LDiufe4vZcUO2f9s',
    appId: '1:830352231306:ios:68f918dcf05678c3b41673',
    messagingSenderId: '830352231306',
    projectId: 'nipibaskettupizarravirtual',
    storageBucket: 'nipibaskettupizarravirtual.firebasestorage.app',
    iosBundleId: 'com.example.nipibasketTupizarravirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZLyOMm_gMsz10QT2LDiufe4vZcUO2f9s',
    appId: '1:830352231306:ios:68f918dcf05678c3b41673',
    messagingSenderId: '830352231306',
    projectId: 'nipibaskettupizarravirtual',
    storageBucket: 'nipibaskettupizarravirtual.firebasestorage.app',
    iosBundleId: 'com.example.nipibasketTupizarravirtual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEUQ_-2MNxJV7GYIUGvHPVLJ1sAr-Dw5I',
    appId: '1:830352231306:web:1b5c8ba13598161ab41673',
    messagingSenderId: '830352231306',
    projectId: 'nipibaskettupizarravirtual',
    authDomain: 'nipibaskettupizarravirtual.firebaseapp.com',
    storageBucket: 'nipibaskettupizarravirtual.firebasestorage.app',
    measurementId: 'G-KFLGNQ4LJR',
  );
}
